

git_repos:
  - {name: "Vundle",
     src: "https://github.com/VundleVim/Vundle.vim.git",
     dst:  ".vim/bundle/Vundle.vim"}

  - {name: "oh-my-zsh",
     src: "https://github.com/robbyrussell/oh-my-zsh.git",
     dst:  ".oh-my-zsh"}

  - {name: "powerlevel10k",
     src: "https://github.com/romkatv/powerlevel10k",
     dst:  ".oh-my-zsh/custom/themes/powerlevel10k"}

dotfiles:
  - {name: "vimrc",
     src: "assets/editor/vimrc.vim",
     dst: ".vimrc"}

  # nvim and vim use the same config
  - {name: "nvim_init",
     src: "assets/editor/vimrc.vim",
     dst: ".config/nvim/init.vim"}

  # bash (mac)
  - {name: "bash_profile",
     src: "assets/shell/bash_profile.sh",
     dst: ".bash_profile"}

  # bash
  - {name: "bashrc",
     src: "assets/shell/bashrc.sh",
     dst: ".bashrc"}

  # zsh
  - {name: "zshrc",
     src: "assets/shell/zshrc.zsh",
     dst: ".zshrc"}

  - {name: "p10k",
     src: "assets/shell/p10k.zsh",
     dst: ".p10k.zsh"}

  - {name: "gitconfig",
     src: "assets/git/gitconfig",
     dst: ".gitconfig"}

  - {name: "tmux",
     src: "assets/tmux/tmux.conf",
     dst: ".tmux.conf"}

  - {name: "tigrc",
     src: "assets/tig/tigrc",
     dst: ".tigrc"}

  - {name: "assets",
     src: "assets",
     dst: ".assets"}
